# This config file is for use with the `build_data` and `check_data` functions,
# which are helpers for implementations of Open SDG. This file allows easy use
# of those functions without altering Python code.

# Languages
# ---------
# This tells sdg-build to perform "translated builds" for each of the specified
# languages. Each build is in its own subfolder - one for each language.
languages:
  - ru
  - kk
  - en

# Translation repositories
# ------------------------
# This tells sdg-build to import translations from Git repositories. Specific
# tags or branches should be indicated after an "@" symbol.
translations:
  - class: TranslationInputSdmx
    source: https://registry.sdmx.org/ws/public/sdmxapi/rest/datastructure/IAEG-SDGs/SDG/latest/?format=sdmx-2.1&detail=full&references=children
  - class: TranslationInputSdgTranslations
    source: https://github.com/open-sdg/sdg-translations.git
    tag: 2.3.0
  - class: TranslationInputYaml
    source: translations

# Source directory
# ----------------
# This identifies the directory that holds the 'data' and 'meta' folders.
# The default, '', points to the root of this repository.
src_dir: ''

# Destination directory
# ---------------------
# This identifies a directory to hold the "built" files. The default is '_site'.
site_dir: _site

# Schema file
# -----------
# This identifies a file containing the schema (possible fields) for metadata.
# Currently this needs to be a prose.io config, and defaults to '_prose.yml'.
schema_file: _prose.yml

# Reporting status extra fields
# -----------------------------
# This allows the build to generate stats for reporting status by additional
# fields, beyond the default "status by goal" report.
reporting_status_extra_fields:
  - un_designated_tier
  - customisation

# Map layers
# ----------
# This allows the build to generate one or more GeoJSON files to be used by
# Open SDG maps. The parameters available correspond to the OutputGeoJson class.
# See sdg/outputs/OutputGeoJson.py for more information.
map_layers:
  - geojson_file: kzgeo.geojson
    name_property: kzName
    id_property: kzCode
    output_subfolder: regions
    filename_prefix: indicator_
  # The above layer will produce GeoJSON files such as this:
  #     _site/en/geojson/regions/indicator_1-2-1.geojson
  # Add any number of additional layers, such as one for counties.

docs_branding: Kazstat SDG data repository
docs_intro: <p>This is a summary of the resources available on this data service.
  This data is used by <a href="http://kazstat.github.io/sdg-site-kazstat">the
  Kazakhstan SDG national reporting platform</a>.</p>
  <p>SDMX data intended for use in the UN global SDG database is
  available <a href="https://kazstat.github.io/sdg-data-kazstat/unsd/sdmx/all.xml">here</a>.
  </p>
docs_indicator_url: http://kazstat.github.io/sdg-site-kazstat/[id]/
docs_translate_disaggregations: true
docs_extra_disaggregations:
  - UNIT_MEASURE
  - SERIES

indicator_options:
  non_disaggregation_columns:
    - Value
    - Year
    - GeoCode
    - SERIES
    - UNIT_MEASURE

inputs:
  - class: InputYamlMeta
    git: false
    path_pattern: indicator-config/*.yml
  - class: InputYamlMeta
    git: true
    path_pattern: meta/*.yml
  - class: InputCsvData
    path_pattern: data/*.csv

logging:
  - warn
